# update_fastlane

###
###  Flutter
###

platform :flutter do
  desc "runs pull request flow"
  lane :pr do
    sh "cd .. && ./fastlane/scripts/tests.sh"
    sh "cd .. && ./fastlane/scripts/coverage.sh"
    sh "cd .. && ./fastlane/scripts/lint.sh"
    run_danger
  end
end

lane :run_danger do
  danger(
    danger_id = "report-coverage",
    dangerfile = "Dangerfile",
    github_api_token: ENV["GITHUB_TOKEN"],
    verbose: true
  )
end