# update_fastlane

###
###  Flutter
###

platform :flutter do
  desc "runs pull request flow"
  lane :pr do
    sh "cd .. && ./fastlane/scripts/tests.sh"
    sh "cd .. && ./fastlane/scripts/coverage.sh"
    sh "cd .. && ./fastlane/scripts/lint.sh"
    run_danger
    commit
  end
end

lane :commit do
  sh("git fetch && git checkout -b docs/bump-coverage")
  git_add(
    path: ["*.txt", "*.md"],
    shell_escape: false
  )
  git_commit(
    path: ["./*.txt", "./*.md"],
    message: "Update documentation"
  )
  push_to_git_remote(
    remote_branch: "master",
    set_upstream: true,
    tags: false
  )
end

lane :run_danger do
  danger(
    danger_id: "report-coverage",
    dangerfile: "Dangerfile",
    github_api_token: ENV["GITHUB_TOKEN"],
    verbose: true
  )
end
